### ISSUE TITLE
How to config testcase.xml

### ISSUE THREAD

**Issue by xiaoxiaojuan** [pmarkert/Pylot#1]
I was trying to send some request, but got 400.. How should I config the testcase.xml?
my message include:
header:
Content-Type :application/json
authorization = BBBB xxxxxxxxxx
device-id = xxxxxxxx

body:
{
    "aaaaa": {
        "header": {
            "xxxx": "xxxxxxxx",
            "name": "xxxxxxx",
            "xxxx": "1111111"
        },
        "xxxxx": {
            "vvvv": 50,
            "vvvv": true
        }
    }
}

**Comment by pmarkert** [comment]
Hello @xiaoxiaojuan,

This project was an early attempt for me to create a way to write multi-step http scripts using data to describe HTTP requests using xml, or json or another similar markup language. I do not actively maintain this project, but it was just a fork of an existing library 'Pylot to make a minor upgrade to use a more user-friendly http library. While I was able to get this project to suit my needs at the time, I have since developed a separate, but much more powerful project called [hyperpotamus](https://github.com/pmarkert/hyperpotamus) which I actively maintain. I'll tell you a bit about hyperpotamus further below so you can see if it might provide a better solution to your challenge, but first let me try to answer your question about Pylot.

If you are getting 400 status-code responses from the server, first, be 100% certain that server properly handles the type of messages you are intending to send. I suggest crafting your request using a different tool such as hyperpotamus or curl or postman where you can see the trace of the request/response to ensure that the server properly handles your messages. If so, then the challenge is to get Pylot to send an equivalent request. I recommend checking the documentation for both [Pylot](https://github.com/mardix/pylot) and [requests](http://docs.python-requests.org/en/master/) which were the two libraries that I combined for this project. Also, the original Pylot project had specific handling for 4xx errors, which I maintained in my modifications, but it would be useful for you to determine if the error you are receiving is a 401, 403, 404, or other 4xx error, because that may tell you if the issue is with the authentication or custom headers or the method. Often the server will return a specific error message.

---

Now let me tell you a bit about hyperpotamus, because that might also be an option for you and I am able to provide more support for that. The advantage to using hyperpotamus is that it not only supports a much richer set of request functionality, but it also allows dynamic tokens to be placed in the request configuration so you can replace parameters easily from .csv, .json, .yaml, user-prompted values, or data captured from previous requests.

To create the request above using hyperpotamus, you would use the following YAML values (JSON also works, but is more verbose):
```yaml
request:
   url: "http://example.com"
   method: POST
   headers:
      device-id: xxxxxxxx
      authorization: BBBB xxxxxxxxxx
   json:
      aaaaa:
         header:
            xxxx: xxxxxxxx
            name: xxxxxxx
            xxxx: 1111111
          xxxxx:
            vvvv: 50
            vvvv: true
```
The above example shows the exact auth-header you had expressed, but there is also an "auth" element that can handle bearer tokens, username/password combinations, and some other typical auth mechanisms. 

For the dynamic portion, you can replace some of those values with macros such as:
```yaml
request:
  # ... abbreviated for clarity ...
  headers:
     device-id: <% device_id %>
       # ... snip ...
       name: <% customer_name %>
```
That way, when  you run your script, you can pass values for those variables in as command-line arguments, or read them from a .csv file (especially if you have multiple records to process), or you could prompt the user to enter the values, or you could even capture the values from part of the response of a previous request. Those macros also support some transformation options such as upper/lower-case, url/base64 encoding and decoding, substrings, and a lot more. Check it out and let me know if that helps.
